name = "MPgenbb"
uuid = "ec4573f6-4a49-49a0-b7a1-8f268f376692"
authors = ["Maros Petro"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"

[targets]
test = ["Test"]
